// <auto-generated />
namespace ServerStockGestion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first_mirgration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_mirgration));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281009219_first_mirgration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
